### PR TITLE
atomicapp tests re-organization

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Comment by cdrage** [comment]
Did you see https://github.com/projectatomic/adb-tests/pull/18 ? :)

**Comment by dustymabe** [comment]
> Did you see #18 ? :)

crap.

**Comment by dustymabe** [comment]
@rtnpro this is the restructure to enable you to easily place a unit-tests directory alongside the functional-tests directory.

**Comment by cdrage** [comment]
LGTM :+1:

**Pull request merged**
